use super::state::AppState;
use super::*;
use crate::config::AppConfig;
use crate::error::{AppError, AppResult};
use crate::runtime_control::RuntimeStatus;
use std::fs;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

fn production_desktop_source() -> &'static str {
    include_str!("desktop.rs")
        .split("#[path = \"desktop_tests.rs\"]")
        .next()
        .unwrap_or_default()
}

fn registered_tauri_commands() -> AppResult<Vec<String>> {
    let handler = production_desktop_source()
        .split_once("tauri::generate_handler![")
        .and_then(|(_, remainder)| remainder.split_once(']'))
        .map(|(handler, _)| handler)
        .ok_or_else(|| AppError::state("Tauri invoke handler must remain discoverable"))?;

    Ok(handler
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(|command| command.trim_end_matches(',').to_string())
        .collect())
}

fn build_manifest_commands() -> AppResult<Vec<String>> {
    let manifest = include_str!("../build.rs")
        .split_once("const APP_COMMANDS: &[&str] = &[")
        .and_then(|(_, remainder)| remainder.split_once("];"))
        .map(|(commands, _)| commands)
        .ok_or_else(|| AppError::state("Tauri build command manifest must remain discoverable"))?;

    Ok(manifest
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix('"')
                .and_then(|command| command.strip_suffix("\","))
                .map(str::to_owned)
        })
        .collect())
}

#[test]
fn tauri_command_names_match_the_shared_contract() -> AppResult<()> {
    let manifest_json = include_str!("../../contracts/tauri-ipc.json");
    let manifest = serde_json::from_str::<serde_json::Value>(manifest_json).map_err(|error| {
        AppError::config(format!("Failed to parse Tauri IPC contract: {error}"))
    })?;
    let mut expected_commands = manifest
        .get("commands")
        .and_then(serde_json::Value::as_object)
        .ok_or_else(|| AppError::config("Tauri IPC contract must define command names"))?
        .values()
        .map(|value| {
            value
                .as_str()
                .map(str::to_owned)
                .ok_or_else(|| AppError::config("Tauri command names must be strings"))
        })
        .collect::<AppResult<Vec<_>>>()?;
    let mut registered_commands = registered_tauri_commands()?;
    let mut build_commands = build_manifest_commands()?;
    expected_commands.sort();
    registered_commands.sort();
    build_commands.sort();

    assert_eq!(registered_commands, expected_commands);
    assert_eq!(build_commands, expected_commands);
    Ok(())
}

#[test]
fn registered_command_handlers_remain_private_to_the_desktop_shell() -> AppResult<()> {
    let desktop = production_desktop_source();

    for command in registered_tauri_commands()? {
        assert!(desktop.contains(&format!("fn {command}(")));
        for visibility in ["pub fn", "pub(crate) fn", "pub(super) fn"] {
            assert!(
                !desktop.contains(&format!("{visibility} {command}(")),
                "registered command leaked outside the desktop shell: {command}"
            );
        }
    }

    Ok(())
}

#[test]
fn runtime_control_snapshot_is_the_only_control_read_command_exposed() {
    let desktop = production_desktop_source();
    let build_manifest = include_str!("../build.rs");
    let desktop_capability = include_str!("../capabilities/default.json");

    assert!(desktop.contains("get_runtime_control_snapshot,"));
    assert!(build_manifest.contains("\"get_runtime_control_snapshot\""));
    assert!(desktop_capability.contains("\"allow-get-runtime-control-snapshot\""));

    for (command, permission) in [
        ("get_app_config", "allow-get-app-config"),
        ("get_runtime_status", "allow-get-runtime-status"),
        ("get_credential_status", "allow-get-credential-status"),
    ] {
        assert!(!desktop.contains(&format!("fn {command}(")));
        assert!(!build_manifest.contains(&format!("\"{command}\"")));
        assert!(!desktop_capability.contains(&format!("\"{permission}\"")));
    }
}

#[test]
fn caption_aggregate_snapshot_command_has_a_narrow_generated_permission() {
    let desktop = production_desktop_source();
    let build_manifest = include_str!("../build.rs");
    let desktop_capability = include_str!("../capabilities/default.json");
    let generated_permission =
        include_str!("../permissions/autogenerated/get_caption_aggregate_snapshot.toml");

    assert!(desktop.contains("get_caption_aggregate_snapshot,"));
    assert!(build_manifest.contains("\"get_caption_aggregate_snapshot\""));
    assert!(desktop_capability.contains("\"allow-get-caption-aggregate-snapshot\""));
    assert!(generated_permission.contains("commands.allow = [\"get_caption_aggregate_snapshot\"]"));
}

#[test]
fn microphone_probe_command_has_a_narrow_generated_permission() {
    let desktop = production_desktop_source();
    let build_manifest = include_str!("../build.rs");
    let desktop_capability = include_str!("../capabilities/default.json");
    let generated_permission = include_str!("../permissions/autogenerated/probe_audio_input.toml");

    assert!(desktop.contains("probe_audio_input,"));
    assert!(build_manifest.contains("\"probe_audio_input\""));
    assert!(desktop_capability.contains("\"allow-probe-audio-input\""));
    assert!(generated_permission.contains("commands.allow = [\"probe_audio_input\"]"));
}

#[test]
#[expect(
    deprecated,
    reason = "Tauri's mock runtime requires one run iteration to execute the production setup hook."
)]
fn desktop_setup_loads_saved_config_before_commands_run() -> AppResult<()> {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_nanos();
    let identifier = format!(
        "com.vrclivecaption.startup-test-{}-{nonce}",
        std::process::id()
    );
    let mut probe_context = tauri::test::mock_context(tauri::test::noop_assets());
    probe_context
        .config_mut()
        .identifier
        .clone_from(&identifier);
    let probe_app = tauri::test::mock_builder()
        .build(probe_context)
        .map_err(|error| AppError::runtime(format!("Failed to build path probe: {error}")))?;
    let config_directory = probe_app
        .path()
        .app_config_dir()
        .map_err(|error| AppError::config_io(format!("Failed to resolve test path: {error}")))?;
    drop(probe_app);

    let mut saved_config = AppConfig::default();
    saved_config.audio.input_device_id = Some("saved-device".to_string());
    saved_config.osc.enabled = false;
    fs::create_dir_all(&config_directory).map_err(|error| {
        AppError::config_io(format!("Failed to create test config directory: {error}"))
    })?;
    let contents = serde_json::to_string(&saved_config).map_err(|error| {
        AppError::config_io(format!("Failed to serialize test config: {error}"))
    })?;
    fs::write(config_directory.join("config.json"), contents)
        .map_err(|error| AppError::config_io(format!("Failed to write test config: {error}")))?;

    let mut context = tauri::test::mock_context(tauri::test::noop_assets());
    context.config_mut().identifier = identifier;
    let mut app = manage_state(tauri::test::mock_builder())
        .build(context)
        .map_err(|error| AppError::runtime(format!("Failed to build test app: {error}")))?;
    app.run_iteration(|_, _| {});
    let loaded_config = app
        .state::<AppState>()
        .runtime_control_snapshot()?
        .desired
        .config;
    let persisted_contents = fs::read_to_string(config_directory.join("config.json"))
        .map_err(|error| AppError::config_io(format!("Failed to read test config: {error}")))?;
    let persisted_config = serde_json::from_str::<serde_json::Value>(&persisted_contents)
        .map_err(|error| AppError::config_io(format!("Failed to parse test config: {error}")))?;
    drop(app);

    fs::remove_dir_all(&config_directory).map_err(|error| {
        AppError::config_io(format!("Failed to remove test config directory: {error}"))
    })?;

    assert_eq!(
        loaded_config.audio.input_device_id.as_deref(),
        Some("saved-device")
    );
    assert!(!loaded_config.osc.enabled);
    assert_eq!(
        persisted_config.pointer("/schemaVersion"),
        Some(&serde_json::json!(crate::config::APP_CONFIG_SCHEMA_VERSION))
    );

    Ok(())
}

#[test]
fn exit_event_stops_the_managed_runtime() -> AppResult<()> {
    let app = manage_state(tauri::test::mock_builder())
        .build(tauri::test::mock_context(tauri::test::noop_assets()))
        .map_err(|error| AppError::runtime(format!("Failed to build test app: {error}")))?;

    handle_run_event(app.handle(), tauri::RunEvent::Exit);

    let snapshot = app.state::<AppState>().runtime_control_snapshot()?;
    assert_eq!(snapshot.runtime_status.status, RuntimeStatus::Stopped);
    Ok(())
}
