use super::*;
use crate::config::AppConfig;
use crate::error::{AppError, AppResult};
use std::fs;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

fn production_lib_source() -> &'static str {
    include_str!("lib.rs")
        .split("#[path = \"lib_tests.rs\"]")
        .next()
        .unwrap_or_default()
}

#[test]
fn runtime_control_snapshot_is_the_only_control_read_command_exposed() {
    let production_lib = production_lib_source();
    let build_manifest = include_str!("../build.rs");
    let desktop_capability = include_str!("../capabilities/default.json");

    assert!(production_lib.contains("commands::get_runtime_control_snapshot"));
    assert!(build_manifest.contains("\"get_runtime_control_snapshot\""));
    assert!(desktop_capability.contains("\"allow-get-runtime-control-snapshot\""));

    for (command, permission) in [
        ("get_app_config", "allow-get-app-config"),
        ("get_runtime_status", "allow-get-runtime-status"),
        (
            "get_provider_secret_status",
            "allow-get-provider-secret-status",
        ),
    ] {
        assert!(!production_lib.contains(&format!("commands::{command}")));
        assert!(!build_manifest.contains(&format!("\"{command}\"")));
        assert!(!desktop_capability.contains(&format!("\"{permission}\"")));
    }
}

#[test]
fn caption_session_snapshot_command_has_a_narrow_generated_permission() {
    let production_lib = production_lib_source();
    let build_manifest = include_str!("../build.rs");
    let desktop_capability = include_str!("../capabilities/default.json");
    let generated_permission =
        include_str!("../permissions/autogenerated/get_caption_session_snapshot.toml");

    assert!(production_lib.contains("commands::get_caption_session_snapshot"));
    assert!(build_manifest.contains("\"get_caption_session_snapshot\""));
    assert!(desktop_capability.contains("\"allow-get-caption-session-snapshot\""));
    assert!(generated_permission.contains("commands.allow = [\"get_caption_session_snapshot\"]"));
}

#[test]
fn microphone_probe_command_has_a_narrow_generated_permission() {
    let production_lib = production_lib_source();
    let build_manifest = include_str!("../build.rs");
    let desktop_capability = include_str!("../capabilities/default.json");
    let generated_permission = include_str!("../permissions/autogenerated/probe_audio_input.toml");

    assert!(production_lib.contains("commands::probe_audio_input"));
    assert!(build_manifest.contains("\"probe_audio_input\""));
    assert!(desktop_capability.contains("\"allow-probe-audio-input\""));
    assert!(generated_permission.contains("commands.allow = [\"probe_audio_input\"]"));
}

#[test]
fn unsaved_changes_dialog_has_a_narrow_message_permission() {
    let production_lib = production_lib_source();
    let desktop_capability = include_str!("../capabilities/default.json");

    assert!(production_lib.contains("tauri_plugin_dialog::init()"));
    assert!(desktop_capability.contains("\"dialog:allow-message\""));

    for permission in ["dialog:default", "dialog:allow-open", "dialog:allow-save"] {
        assert!(!desktop_capability.contains(&format!("\"{permission}\"")));
    }
}

#[test]
#[expect(
    deprecated,
    reason = "Tauri's mock runtime requires one run iteration to execute the production setup hook."
)]
fn builder_setup_loads_saved_config_before_commands_run() -> AppResult<()> {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_nanos();
    let identifier = format!(
        "com.vrclivecaption.startup-test-{}-{nonce}",
        std::process::id()
    );
    let mut probe_context = tauri::test::mock_context(tauri::test::noop_assets());
    probe_context
        .config_mut()
        .identifier
        .clone_from(&identifier);
    let probe_app = tauri::test::mock_builder()
        .build(probe_context)
        .map_err(|error| AppError::runtime(format!("Failed to build path probe: {error}")))?;
    let config_directory = probe_app
        .path()
        .app_config_dir()
        .map_err(|error| AppError::config_io(format!("Failed to resolve test path: {error}")))?;
    drop(probe_app);

    let mut saved_config = AppConfig::default();
    saved_config.audio.input_device_id = Some("saved-device".to_string());
    saved_config.osc.enabled = false;
    fs::create_dir_all(&config_directory).map_err(|error| {
        AppError::config_io(format!("Failed to create test config directory: {error}"))
    })?;
    let contents = serde_json::to_string(&saved_config).map_err(|error| {
        AppError::config_io(format!("Failed to serialize test config: {error}"))
    })?;
    fs::write(config_directory.join("config.json"), contents)
        .map_err(|error| AppError::config_io(format!("Failed to write test config: {error}")))?;

    let mut context = tauri::test::mock_context(tauri::test::noop_assets());
    context.config_mut().identifier = identifier;
    let mut app = configure_builder(tauri::test::mock_builder())
        .build(context)
        .map_err(|error| AppError::runtime(format!("Failed to build test app: {error}")))?;
    app.run_iteration(|_, _| {});
    let loaded_config = app
        .state::<state::AppState>()
        .runtime_control_snapshot()?
        .desired
        .config;
    let persisted_contents = fs::read_to_string(config_directory.join("config.json"))
        .map_err(|error| AppError::config_io(format!("Failed to read test config: {error}")))?;
    let persisted_config = serde_json::from_str::<serde_json::Value>(&persisted_contents)
        .map_err(|error| AppError::config_io(format!("Failed to parse test config: {error}")))?;
    drop(app);

    fs::remove_dir_all(&config_directory).map_err(|error| {
        AppError::config_io(format!("Failed to remove test config directory: {error}"))
    })?;

    assert_eq!(
        loaded_config.audio.input_device_id.as_deref(),
        Some("saved-device")
    );
    assert!(!loaded_config.osc.enabled);
    assert_eq!(
        persisted_config.pointer("/schemaVersion"),
        Some(&serde_json::json!(crate::config::APP_CONFIG_SCHEMA_VERSION))
    );

    Ok(())
}
